### ISSUE TITLE
Move type-piracy on startwith/endswith  to Compat.jl

### ISSUE THREAD

**Issue by oxinabox** [invenia/Wrangling.jl#4]
I think this is a good point and we need to settle it before v1.0 of the package

_Originally posted  in https://github.com/invenia/Wrangling.jl/pull/3_

### @KristofferC:

> Just namespace these inside `Wrangler` and have people do `import Wrangler.startswith` to opt into your version of the functions? No need for type piracy.

### @oxinabox:

> 
> I debated this option. It ones one of a few, others being type-piracy, and making up new names `prefixedby` and `suffixedby`
> 
> I would have said it as putting in the docs telling people to always do:
> ```
> using Wrangingly
> using Wranging: startswith, endswith
> ```
> 
> rather than just `using Wrangling`.
> 
> I think @nickrobinson251  convinced me that type-piracy was the least bad of many options
> 

### @nickrobinson251:

> 
> yeah... i'm no longer sure type-piracy is the best option. But 🤷‍♂
> 
> My thinking was:
> 
> -  The alternatively-named-function feels a bad compromise because they are really the exact same as startswith/endswith... so they really should be methods of those functions.
> -  But introducing the name-clash with Base is also pretty un-fun for users.
> -  Which leaves us with type-piracy... and this is the least-bad version of that bad thing
>

**Comment by oxinabox** [comment]
Type-piracy would be fine (/should move to Compat.jl) if the following julia issues are resolve in favor of doing this in `Base`
https://github.com/JuliaLang/julia/issues/33193
https://github.com/JuliaLang/julia/issues/35033

**Comment by oxinabox** [comment]
These have been done in Julia 1.5. this need to be moved to Compat.jl

**Comment by nickrobinson251** [comment]
xref #14

**Comment by nickrobinson251** [comment]
the 1-arg / "curried" versions of `startswith`/`endswith` should move to Compat.jl (following https://github.com/JuliaLang/julia/pull/35052). The `Symbol` piracy stays here.

**Comment by nickrobinson251** [comment]
https://github.com/JuliaLang/Compat.jl/pull/719
